ENV['RCT_NEW_ARCH_ENABLED'] = '1'

platform :ios, '13.4'

linkage = ENV['USE_FRAMEWORKS']
if linkage
  use_frameworks! :linkage => linkage.to_sym
end

target 'CasExample' do  
  pod 'react-native-cas', :path => File.join(__dir__, '../../')

  post_install do |installer|    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
